"""Added repo_link and demo_link column to Projects

Revision ID: f20d6e43c752
Revises: 
Create Date: 2024-10-25 06:54:23.086516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20d6e43c752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('demo_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_column('demo_link')
        batch_op.drop_column('repo_link')

    # ### end Alembic commands ###
